export const CHECK_IF_MOBILE = 'CHECK_IF_MOBILE'
export const CHECK_BROWSER = 'CHECK_BROWSER'
export const CHECK_IF_IE = 'CHECK_IF_IE'
export const GET_VP_DIMS = 'GET_VP_DIMS'
export const LOCK_ORIENTATION = 'LOCK_ORIENTATION'

export const GET_USER_LOCATION = 'GET_USER_LOCATION'
export const SET_MAP_CENTER = 'SET_MAP_CENTER'
export const SET_MAP_MARKERS = 'SET_MAP_MARKERS'
export const SET_MAP_ZOOM = 'SET_MAP_ZOOM'

export const SET_ACTIVE_LOCATION = 'SET_ACTIVE_LOCATION'
export const SET_ACTIVE_RESULTS_LIST = 'SET_ACTIVE_RESULTS_LIST'
